/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import almacenamiento.controlador.ControlCausa;
import clinicadb.ClinicaDB;
import java.sql.Connection;
import javax.swing.JOptionPane;
import proceso.Medico;

/**
 *
 * @author daniel
 */
public class PanelMedico extends javax.swing.JFrame {

    /**
     * Creates new form PanelMedico
     */
    static ClinicaDB db; //TEMPORAL
    private PanelCausas panelCausas; 
    private PanelHistoriaClinica panelHC;
    private Connection conn;
    private PanelRegistros panelReg;
    private Medico doctor;
    private PanelFormula panelFormula;
    private PanelCampana panelCampana;
    public PanelMedico(Connection conn,Medico med) {
        super("Panel Administrativo para Doctores");
        initComponents();
        lbTitulo.setText("Bienvenido Dr "+med.getApellidos()+"!");
        this.conn=conn;
        setResizable(false);
        doctor=med;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btCrearHC = new javax.swing.JButton();
        btRegistro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btFormula = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btCrearCausa = new javax.swing.JButton();
        btEditarCausa = new javax.swing.JButton();
        btEliminarCausa = new javax.swing.JButton();
        btCerrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btCrearCampana = new javax.swing.JButton();
        btEditarCampana = new javax.swing.JButton();
        btEliminarCampana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lbTitulo.setText("Bienvenido Dr !");

        jLabel2.setText("En este panel usted podra gestionar Historias Clinicas, formulas medicas y causas de cita ");

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel3.setText("Gestion de Historias Clinicas");

        btCrearHC.setText("Crear");
        btCrearHC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearHCActionPerformed(evt);
            }
        });

        btRegistro.setText("Ingresar Registro");
        btRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setText("Gestion de Formulas Medicas");

        btFormula.setText("Nueva Formula");
        btFormula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFormulaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel4.setText("Gestion de Causas de Cita");

        btCrearCausa.setText("Crear");
        btCrearCausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearCausaActionPerformed(evt);
            }
        });

        btEditarCausa.setText("Editar");
        btEditarCausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarCausaActionPerformed(evt);
            }
        });

        btEliminarCausa.setText("Eliminar");
        btEliminarCausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarCausaActionPerformed(evt);
            }
        });

        btCerrar.setText("Cerrar Sesion");
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel6.setText("Gestion de Campañas");

        btCrearCampana.setText("Crear");
        btCrearCampana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearCampanaActionPerformed(evt);
            }
        });

        btEditarCampana.setText("Editar");
        btEditarCampana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarCampanaActionPerformed(evt);
            }
        });

        btEliminarCampana.setText("Eliminar");
        btEliminarCampana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarCampanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCrearHC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(btFormula, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btCrearCausa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(btEditarCausa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btEliminarCausa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lbTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCrearCampana, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btEditarCampana, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btEliminarCampana, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCerrar)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCrearHC)
                            .addComponent(btFormula)
                            .addComponent(btCrearCausa))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btRegistro)
                            .addComponent(btEditarCausa)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(btEliminarCausa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCrearCampana)
                    .addComponent(btEditarCampana)
                    .addComponent(btEliminarCampana))
                .addGap(22, 22, 22)
                .addComponent(btCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistroActionPerformed
        // TODO add your handling code here:
        panelReg = new PanelRegistros(conn,doctor);
        panelReg.setVisible(true);
    }//GEN-LAST:event_btRegistroActionPerformed

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
        // TODO add your handling code here:
        //TEMPORAL 
        db.cerrar();
        System.exit(0);
        
    }//GEN-LAST:event_btCerrarActionPerformed

    private void btCrearCausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearCausaActionPerformed
        // TODO add your handling code here:
        panelCausas = new PanelCausas(1,conn);
        panelCausas.setVisible(true);
    }//GEN-LAST:event_btCrearCausaActionPerformed

    private void btEditarCausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarCausaActionPerformed
        // TODO add your handling code here:
        panelCausas = new PanelCausas(2,conn);
        int len = panelCausas.tamCausas();
        if(len==0){
            JOptionPane.showMessageDialog(this, "No hay causas registradas en este momento","Mensaje",JOptionPane.ERROR_MESSAGE);
        }else{
            panelCausas.setVisible(true);
        }
        
    }//GEN-LAST:event_btEditarCausaActionPerformed

    private void btEliminarCausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarCausaActionPerformed
        // TODO add your handling code here:
        panelCausas = new PanelCausas(3,conn);
          int len = panelCausas.tamCausas();
        if(len==0){
            JOptionPane.showMessageDialog(this, "No hay causas registradas en este momento","Mensaje",JOptionPane.ERROR_MESSAGE);
        }else{
            panelCausas.setVisible(true);
        }
    }//GEN-LAST:event_btEliminarCausaActionPerformed

    private void btCrearHCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearHCActionPerformed
        // TODO add your handling code here:
        panelHC = new PanelHistoriaClinica(conn);
        panelHC.setVisible(true);
    }//GEN-LAST:event_btCrearHCActionPerformed

    private void btFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFormulaActionPerformed
        // TODO add your handling code here:
        //Formulas medicas 
        panelFormula = new PanelFormula(conn,doctor);
        panelFormula.setVisible(true);
    }//GEN-LAST:event_btFormulaActionPerformed

    private void btCrearCampanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearCampanaActionPerformed
        // TODO add your handling code here:
        panelCampana = new PanelCampana(1, doctor, conn);
        panelCampana.setVisible(true);
        
    }//GEN-LAST:event_btCrearCampanaActionPerformed

    private void btEditarCampanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarCampanaActionPerformed
        // TODO add your handling code here:
        panelCampana = new PanelCampana(2, doctor, conn);
        int len = panelCampana.tamCampanas();
        if(len==0){
            JOptionPane.showMessageDialog(this, "No hay campañas registradas en este momento","Mensaje",JOptionPane.ERROR_MESSAGE);
        }else{
            panelCampana.setVisible(true);
        }
    }//GEN-LAST:event_btEditarCampanaActionPerformed

    private void btEliminarCampanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarCampanaActionPerformed
        // TODO add your handling code here:
        panelCampana = new PanelCampana(3, doctor, conn);
        int len = panelCampana.tamCampanas();
        if(len==0){
            JOptionPane.showMessageDialog(this, "No hay campañas registradas en este momento","Mensaje",JOptionPane.ERROR_MESSAGE);
        }else{
            panelCampana.setVisible(true);
        }
    }//GEN-LAST:event_btEliminarCampanaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //TEMPORAL
         db = new ClinicaDB();
        final Connection conn = db.conectar();
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Medico med = new Medico("Daniel", "Correa", "31245","calle univalle", 350, "danielc.web@gmail.com", "Doc", "1144067772", 12, "Sistemas", "Univalle");
                new PanelMedico(conn,med).setVisible(true);
                //new PanelSecretaria(conn).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCerrar;
    private javax.swing.JButton btCrearCampana;
    private javax.swing.JButton btCrearCausa;
    private javax.swing.JButton btCrearHC;
    private javax.swing.JButton btEditarCampana;
    private javax.swing.JButton btEditarCausa;
    private javax.swing.JButton btEliminarCampana;
    private javax.swing.JButton btEliminarCausa;
    private javax.swing.JButton btFormula;
    private javax.swing.JButton btRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
