/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.sql.Connection;

/**
 *
 * @author alvaromartinez
 */
public class PanelEnfermera extends javax.swing.JFrame {

    /**
     * Creates new form PanelEnfermera
     */
    
        PanelCRUDCama ventCama;
        PanelAsigCamas ventAsigCam;
        private Connection conn;

    public PanelEnfermera(Connection conn) {
        this.conn = conn;
        initComponents();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        infoPanel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btCrearCama = new javax.swing.JButton();
        btModifCama = new javax.swing.JButton();
        btElimCama = new javax.swing.JButton();
        btAsigPac = new javax.swing.JButton();
        btElmPac = new javax.swing.JButton();
        tituPaci = new javax.swing.JLabel();
        tituloCita = new javax.swing.JLabel();
        btAsignCama = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/logo2.png"))); // NOI18N

        lbTitulo.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lbTitulo.setText("Bienvenido");

        infoPanel.setText("En este panel usted podra gestion de camas y campañas");

        jSeparator1.setMaximumSize(new java.awt.Dimension(290, 290));

        btCrearCama.setText("Crear");
        btCrearCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearCamaActionPerformed(evt);
            }
        });

        btModifCama.setText("Modificar");
        btModifCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifCamaActionPerformed(evt);
            }
        });

        btElimCama.setText("Eliminar");
        btElimCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btElimCamaActionPerformed(evt);
            }
        });

        btAsigPac.setText("Asignar Paciente");
        btAsigPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAsigPacActionPerformed(evt);
            }
        });

        btElmPac.setText("Eliminar Paciente");

        tituPaci.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        tituPaci.setText("Gestion de Camas");

        tituloCita.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        tituloCita.setText("Gestion de Campañas");

        btAsignCama.setText("Asignar Paciente");
        btAsignCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAsignCamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitulo)
                    .addComponent(infoPanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(tituPaci, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btAsignCama, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(btElimCama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btModifCama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCrearCama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloCita, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btElmPac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addComponent(btAsigPac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLogo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituPaci)
                    .addComponent(tituloCita))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAsigPac)
                    .addComponent(btCrearCama))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btElmPac))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btModifCama)
                        .addGap(18, 18, 18)
                        .addComponent(btElimCama)))
                .addGap(18, 18, 18)
                .addComponent(btAsignCama)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCrearCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearCamaActionPerformed
        ventCama = new PanelCRUDCama(conn, 1);
        ventCama.setVisible(true);
    }//GEN-LAST:event_btCrearCamaActionPerformed

    private void btModifCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifCamaActionPerformed
        ventCama = new PanelCRUDCama(conn, 2);
        ventCama.setVisible(true);
    }//GEN-LAST:event_btModifCamaActionPerformed

    private void btElimCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btElimCamaActionPerformed
        ventCama = new PanelCRUDCama(conn, 3);
        ventCama.setVisible(true);
    }//GEN-LAST:event_btElimCamaActionPerformed

    private void btAsignCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAsignCamaActionPerformed
        ventAsigCam = new PanelAsigCamas(conn);
        ventAsigCam.setVisible(true);
    }//GEN-LAST:event_btAsignCamaActionPerformed

    private void btAsigPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAsigPacActionPerformed
        PanelPacCampa vistaCamp = new PanelPacCampa(conn);
        vistaCamp.setVisible(true);
    }//GEN-LAST:event_btAsigPacActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAsigPac;
    private javax.swing.JButton btAsignCama;
    private javax.swing.JButton btCrearCama;
    private javax.swing.JButton btElimCama;
    private javax.swing.JButton btElmPac;
    private javax.swing.JButton btModifCama;
    private javax.swing.JLabel infoPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel tituPaci;
    private javax.swing.JLabel tituloCita;
    // End of variables declaration//GEN-END:variables
}
