/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import almacenamiento.controlador.ControlFormula;
import java.sql.Connection;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import proceso.Formula;
import proceso.HistoriaClinica;
import proceso.Medicamento;
import proceso.Medico;
import proceso.Paciente;

/**
 *
 * @author daniel
 */
public class PanelFormula extends javax.swing.JFrame {

    private double costo=0; 
    private Date hoy;
    private Connection conn;
    private Medico doctor;
    private Medicamento[] medicamentos;
    private String[] nomMedicamentos;
    private boolean[] medicamentosSeleccionados;
    private Vector<Medicamento> medicamentosDelRegistro;    
    private HistoriaClinica historia;
    private ControlFormula control;
    /**
     * Creates new form PanelFormula
     */
    public PanelFormula(Connection conn , Medico doctor) {
        super("Formulas Medicas: Generar");
        setResizable(false);
        initComponents();
        hoy = new Date();
        this.conn=conn;
        this.doctor=doctor;
        btCrear.setEnabled(false);
        String fecha = hoy.toString();
        lbFecha.setText(fecha);
        medicamentosDelRegistro = new Vector<Medicamento>();
        lbPaciente.setText("");
        historia=null;
        control = new ControlFormula(conn);
        mostrarMedicamentos();
                
        
    }
    private void mostrarMedicamentos(){
        medicamentos = control.listarMedicamentos();
        
        int longitud=medicamentos.length;
        nomMedicamentos=new String[longitud];
        medicamentosSeleccionados = new boolean[longitud];
        for(int i=0; i<longitud; i++){
            String nombre=medicamentos[i].getNombre();
            System.out.println(nombre);
            nomMedicamentos[i]=nombre;
            medicamentosSeleccionados[i] = false;
        }
        cbMedicamentos.setModel(new javax.swing.DefaultComboBoxModel(nomMedicamentos));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfCedula = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbPaciente = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbCosto = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbMedicamentos = new javax.swing.JComboBox();
        btAgregar = new javax.swing.JButton();
        btQuitar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSeleccionados = new javax.swing.JTextArea();
        btCrear = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Formulas Medicas: Generar");

        jLabel2.setText("Este panel le permite crear formulas medicas");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Historia Clinica:");

        jLabel4.setText("Paciente:");

        tfCedula.setText("Cedula");

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Nombres y Apellidos:");

        lbPaciente.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        lbPaciente.setText("salida");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("Fecha:");

        lbFecha.setText("hoy");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("Costo Acumulado:");

        lbCosto.setText("$ 0");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setText("Medicamentos:");

        btAgregar.setText("Agregar");
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });

        btQuitar.setText("Quitar");
        btQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuitarActionPerformed(evt);
            }
        });

        jLabel9.setText("Medicamentos adicionados al registro:");

        taSeleccionados.setEditable(false);
        taSeleccionados.setColumns(20);
        taSeleccionados.setRows(5);
        jScrollPane1.setViewportView(taSeleccionados);

        btCrear.setText("Crear");
        btCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btBuscar))
                            .addComponent(jLabel6)
                            .addComponent(lbFecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCosto)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btQuitar))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCancelar)
                .addGap(18, 18, 18)
                .addComponent(btCrear)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar)
                    .addComponent(jLabel5)
                    .addComponent(lbPaciente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFecha)
                    .addComponent(lbCosto))
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAgregar)
                    .addComponent(btQuitar))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCrear)
                    .addComponent(btCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
        // TODO add your handling code here:
        int index = cbMedicamentos.getSelectedIndex();
        
        if(medicamentosSeleccionados[index]){
            JOptionPane.showMessageDialog(this, "Esta causa ya esta adicionada en el registro","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            Medicamento seleccionado = medicamentos[index];
            medicamentosSeleccionados[index]=true;
            medicamentosDelRegistro.add(seleccionado);
            taSeleccionados.append(nomMedicamentos[index]+"\n");
            costo+=seleccionado.getCosto();
            lbCosto.setText("$ "+costo);
        }
    }//GEN-LAST:event_btAgregarActionPerformed

    private void btQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuitarActionPerformed
        // TODO add your handling code here:
        int index = cbMedicamentos.getSelectedIndex();
        if(!medicamentosSeleccionados[index]){
            JOptionPane.showMessageDialog(this, "Esta causa no esta adicionada en el registro","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            Medicamento seleccionado = medicamentos[index];
            medicamentosSeleccionados[index]=false;
            medicamentosDelRegistro.remove(seleccionado);
            taSeleccionados.setText("");
            escribirTxtArea();
            costo-=seleccionado.getCosto();
            lbCosto.setText("$ "+costo);
        }
    }//GEN-LAST:event_btQuitarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        String cedula = tfCedula.getText();
        historia = control.buscarHistoria(cedula);
        if(historia.getNumHistoria()==null){
            historia=null;
            JOptionPane.showMessageDialog(this, "No existe una HistoriaClinica para ese paciente\nDebe crear una","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            btCrear.setEnabled(true);
            Paciente paciente = historia.getPersona();
            String nombre = paciente.getNombres().toUpperCase();
            String apellido = paciente.getApellidos().toUpperCase();
            lbPaciente.setText(nombre+" "+apellido);
            //lbNombreApellido.setText("");
        }
    }//GEN-LAST:event_btBuscarActionPerformed
    private boolean validarVacios(){
        boolean resultado = false;
        if(medicamentosDelRegistro.isEmpty()){
            resultado=true;
        }
        return resultado;
    }
    private void btCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearActionPerformed
        // TODO add your handling code here:
        if(validarVacios()){
           JOptionPane.showMessageDialog(this, "Hay campos vacios\nNo puede crearse una formula sin medicamentos","Error",JOptionPane.ERROR_MESSAGE); 
        }else{
            Formula formula = new Formula(doctor, medicamentosDelRegistro, historia, hoy);
            int resul = control.crearFormula(formula);
            if(resul==1){
                JOptionPane.showMessageDialog(this, "Formula creada exitosamente ","Registro Exitoso",JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
        
    }//GEN-LAST:event_btCrearActionPerformed
    private void escribirTxtArea() {
        int size = medicamentosDelRegistro.size();
        for(int i =0;i<size;i++){
            taSeleccionados.append(medicamentosDelRegistro.get(i).getNombre() +"\n");
        }
    }
    /**
     * @param args the command line arguments
     *//*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *//*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form *//*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelFormula().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCrear;
    private javax.swing.JButton btQuitar;
    private javax.swing.JComboBox cbMedicamentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbCosto;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbPaciente;
    private javax.swing.JTextArea taSeleccionados;
    private javax.swing.JTextField tfCedula;
    // End of variables declaration//GEN-END:variables
}
