/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import almacenamiento.controlador.ControlMedicamento;
import java.sql.Connection;
import javax.swing.JOptionPane;
import proceso.Medicamento;

/**
 *
 * @author daniel
 */
public class PanelMedicamentos extends javax.swing.JFrame {

    private ControlMedicamento control;
    private Medicamento[] medicamentos;
    private Medicamento seleccionado;
    private String[] nomMedicamentos;
    private int tipo;
    /**
     * Creates new form PanelMedicamentos
     */
    public PanelMedicamentos(ControlMedicamento control, int tipo) {
        super("Panel de Medicamentos");
        setResizable(false);
        this.control=control;
        initComponents();
        lbEstado.setVisible(false);
        cbEstado.setVisible(false);
        this.tipo=tipo;
        if(tipo==1){
            //Crear
            cbMedicamentos.setVisible(false);
            lbMedicamento.setVisible(false);
            lbTipo.setText("Crear");
            btProceso.setText("Crear");
        }else{
            btProceso.setEnabled(false);
            mostrarMedicamentos();
            if(tipo==2){
                //editar
                lbTipo.setText("Editar");
                btProceso.setText("Editar");
            }else{
                //eliminar
                lbTipo.setText("Eliminar");
                btProceso.setText("Eliminar");
                tfCodigo.setEnabled(false);
                tfNombre.setEnabled(false);
                tfCosto.setEnabled(false);
                taDescript.setEditable(false);
            }
        }
        this.setResizable(false);
    }
    public int tamMedicamentos(){
        return medicamentos.length;
    }
    private void mostrarMedicamentos(){
        if(tipo==2){
            medicamentos = control.listarMedicamentos(false);
        }else{
            medicamentos = control.listarMedicamentos(true);
        }
        
        int longitud=medicamentos.length;
        nomMedicamentos=new String[longitud];
        for(int i=0; i<longitud; i++){
            String nombre=medicamentos[i].getNombre();
            System.out.println(nombre);
            nomMedicamentos[i]=nombre;
        }
        cbMedicamentos.setModel(new javax.swing.DefaultComboBoxModel(nomMedicamentos));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbTipo = new javax.swing.JLabel();
        lbMedicamento = new javax.swing.JLabel();
        cbMedicamentos = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfCodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfCosto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescript = new javax.swing.JTextArea();
        btProceso = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        lbEstado = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setText("Panel de Medicamentos");

        jLabel3.setText("Este modulo le permitira hacer la gestion de medicamentos en el sistema: ");

        lbTipo.setText("tipo");

        lbMedicamento.setText("Medicamentos:");

        cbMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMedicamentosActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre:");

        jLabel6.setText("Codigo:");

        jLabel7.setText("Costo:");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 2, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("<html>Valor sin comas. Puntos para valores decimales<html>");

        jLabel9.setText("Descripcion:");

        taDescript.setColumns(20);
        taDescript.setRows(5);
        jScrollPane1.setViewportView(taDescript);

        btProceso.setText("Guardar");
        btProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcesoActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        lbEstado.setText("Estado:");

        jLabel2.setText("[Crear,Editar,Elminiar]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMedicamento)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbEstado)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1))
                                .addComponent(jLabel7)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(31, 31, 31)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbTipo))
                                .addComponent(jLabel2)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 34, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTipo))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMedicamento)
                    .addComponent(cbMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstado)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tfCosto)
                            .addGap(6, 6, 6))
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btProceso))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void cbMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMedicamentosActionPerformed
        // TODO add your handling code here:
        btProceso.setEnabled(true);
        int index = cbMedicamentos.getSelectedIndex();
        seleccionado = medicamentos[index];
        String codigo = seleccionado.getCodigoMedicamento();
        String nombre = seleccionado.getNombre();
        String descripcion = seleccionado.getDescripcion();
        double costo = seleccionado.getCosto();
        
        tfCodigo.setText(codigo);
        tfNombre.setText(nombre);
        taDescript.setText(descripcion);
        tfCosto.setText(costo+"");
        boolean estado = seleccionado.getEstado();
        System.out.println("seleccionado:"+nombre+" estado:"+estado);
        if(tipo==2 && estado==false){
            lbEstado.setVisible(true);
            cbEstado.setVisible(true);
            cbEstado.addItem("Inactivo");
            cbEstado.addItem("Activo");
            
        }
    }//GEN-LAST:event_cbMedicamentosActionPerformed
    private boolean validarVacios(){
        if(tfNombre.getText().length() == 0 || taDescript.getText().length()==0 || tfCodigo.getText().length()==0 || tfCosto.getText().length()==0){
            return true;
        }else{
            return false;
        }
        
    }
    private void btProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcesoActionPerformed
        // TODO add your handling code here:
        if(validarVacios()){
            JOptionPane.showMessageDialog(this, "Hay campos vacios , no se puede procesar","Error",JOptionPane.ERROR_MESSAGE);
            
        }else{
            String codigo = tfCodigo.getText();
            String nombre = tfNombre.getText();
            double costo = Double.parseDouble(tfCosto.getText());
            String descripcion = taDescript.getText();
            
            Medicamento nuevo = new Medicamento(codigo, nombre, costo, descripcion);
            
            if(tipo==1){
                //crear
                
                int result = control.crearMedicamento(nuevo);
                if(result==1){
                    JOptionPane.showMessageDialog(this, "Medicamento registrado exitosamente","Regitro Existoso",JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Ocurrio un error , no se puede procesar\nVuelve a intentarlo","Error",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                if(tipo==2){
                    //editar
                    String exCod = seleccionado.getCodigoMedicamento();
                    if(!seleccionado.getEstado()){
                        Object item = cbEstado.getSelectedItem();
                            String value = item.toString();
                            
                            if(value.equals("Inactivo")){
                                nuevo.setEstado(false);
                                
                            }
                    }
                    int result = control.actualizarMedicamento(exCod, nuevo);
                    if(result==1){
                        JOptionPane.showMessageDialog(this, "Medicamentos Actualizado exitosamente","Regitro Existoso",JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this, "Ocurrio un error , no se puede procesar\nVuelve a intentarlo","Error",JOptionPane.ERROR_MESSAGE);
                    }
                    
                }else{
                    //eliminar
                    int result = control.eliminarMedicamento(codigo);
                    if(result==1){
                        JOptionPane.showMessageDialog(this, "Medicamento Eliminado exitosamente","Regitro Existoso",JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this, "Ocurrio un error , no se puede procesar\nVuelve a intentarlo","Error",JOptionPane.ERROR_MESSAGE);
                    }
                     
                }
            }
        }
    }//GEN-LAST:event_btProcesoActionPerformed

    /**
     * @param args the command line arguments
     *//*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *//*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form *//*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelMedicamentos("Daniel").setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btProceso;
    private javax.swing.JComboBox cbEstado;
    private javax.swing.JComboBox cbMedicamentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbMedicamento;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JTextArea taDescript;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfCosto;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
