/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import almacenamiento.controlador.ControlArea;
import almacenamiento.controlador.ControlEmpleado;
import almacenamiento.controlador.ControlEnfermera;
import almacenamiento.controlador.ControlMedico;
import java.sql.Connection;
import javax.swing.JOptionPane;
import proceso.Area;
import proceso.Empleado;
import proceso.Enfermera;
import proceso.Medico;

/**
 *
 * @author family
 */
public class VistaEditarUsuario extends javax.swing.JFrame {

    ControlEmpleado ce;
    ControlMedico cm;
    ControlEnfermera cEnf;
    ControlArea ca;
    Connection conn;
    int tipo;

    /**
     * Creates new form VistaEditarUsuario
     *
     * @param controlEm control del empleado
     * @param tipo 1 si es editar y 2 si es eliminar
     */
    public VistaEditarUsuario(ControlEmpleado controlEm, int tipo) {
        this.tipo = tipo;
        initComponents();
        ce = controlEm;
        conn = ce.getConn();
        cm = new ControlMedico(conn);
        ca = new ControlArea(conn);
        cEnf = new ControlEnfermera(conn);

        this.setResizable(false);
        lbIdJ.setVisible(false);
        tfIdJ.setVisible(false);
        lbAnos.setVisible(false);
        comboAnos.setVisible(false);
        lbNL.setVisible(false);
        tfNL.setVisible(false);
        lbEspecialidad.setVisible(false);
        tfEspecialidad.setVisible(false);
        lbUniversidad.setVisible(false);
        tfUniversidad.setVisible(false);
        lbHabs1.setVisible(false);
        lbHabs2.setVisible(false);
        jScrollPane1.setVisible(false);
        if (tipo == 2) {//eliminar
            cbAJ.setEnabled(false);
            comboAnos.setEnabled(false);
            comboCargo.setEnabled(false);
            comboEstado.setEnabled(false);
            taHabs.setEnabled(false);
            tfApellidos.setEnabled(false);
            tfArea.setEnabled(false);
            tfContrasena.setEnabled(false);
            tfDireccion.setEnabled(false);
            tfEmail.setEnabled(false);
            tfEspecialidad.setEnabled(false);
            tfIdJ.setEnabled(false);
            tfNL.setEnabled(false);
            tfNombres.setEnabled(false);
            tfSalario.setEnabled(false);
            tfTelefono.setEnabled(false);
            tfUniversidad.setEnabled(false);
            bModificar.setText("Eliminar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboEstado = new javax.swing.JComboBox();
        btBuscar = new javax.swing.JButton();
        lbEstado = new javax.swing.JLabel();
        tfBuscarId = new javax.swing.JTextField();
        tfNombres = new javax.swing.JTextField();
        tfApellidos = new javax.swing.JTextField();
        lbInfo = new javax.swing.JLabel();
        lbCargo = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        lbBuscar = new javax.swing.JLabel();
        lblNomUsuario = new javax.swing.JLabel();
        lbNombres = new javax.swing.JLabel();
        lbApellidos = new javax.swing.JLabel();
        btCancelar = new javax.swing.JButton();
        lbTelefono = new javax.swing.JLabel();
        bModificar = new javax.swing.JButton();
        tfSalario = new javax.swing.JTextField();
        lbDireccion = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        comboCargo = new javax.swing.JComboBox();
        lblConvocatoria1 = new javax.swing.JLabel();
        tfContrasena = new javax.swing.JTextField();
        lbArea = new javax.swing.JLabel();
        tfArea = new javax.swing.JTextField();
        lbIdJ = new javax.swing.JLabel();
        tfIdJ = new javax.swing.JTextField();
        cbAJ = new javax.swing.JCheckBox();
        comboAnos = new javax.swing.JComboBox();
        lbAnos = new javax.swing.JLabel();
        tfNL = new javax.swing.JTextField();
        lbNL = new javax.swing.JLabel();
        tfEspecialidad = new javax.swing.JTextField();
        lbEspecialidad = new javax.swing.JLabel();
        tfUniversidad = new javax.swing.JTextField();
        lbUniversidad = new javax.swing.JLabel();
        lbHabs1 = new javax.swing.JLabel();
        lbHabs2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taHabs = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        lbEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbEstado.setText("Estado:");

        tfBuscarId.setText("Busqueda por identificación del usuario");
        tfBuscarId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfBuscarIdMouseClicked(evt);
            }
        });
        tfBuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarIdActionPerformed(evt);
            }
        });

        tfNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombresActionPerformed(evt);
            }
        });

        lbInfo.setText("Busque el usuario a editar, haga las ediciones y guarde para modificar");

        lbCargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCargo.setText("Cargo:");

        lbTitulo.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lbTitulo.setText("Editar Usuario");

        lbBuscar.setText("Buscar:");

        lblNomUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNomUsuario.setText("Salario:");

        lbNombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNombres.setText("Nombres:");

        lbApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbApellidos.setText("Apellidos:");

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        lbTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTelefono.setText("Teléfono:");

        bModificar.setText("Modificar");
        bModificar.setMaximumSize(new java.awt.Dimension(74, 29));
        bModificar.setMinimumSize(new java.awt.Dimension(74, 29));
        bModificar.setPreferredSize(new java.awt.Dimension(74, 29));
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        lbDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbDireccion.setText("Dirección:");

        lbEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbEmail.setText("Email:");

        lbLogo.setIcon(new javax.swing.ImageIcon("/home/family/Proyectos/ProyectoDB/ClinicaDB/src/presentacion/logo2.png")); // NOI18N

        tfDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDireccionActionPerformed(evt);
            }
        });

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        tfTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefonoActionPerformed(evt);
            }
        });

        comboCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gerente", "Medico", "Enfermera", "Secretaria", "Bodeguero", "Administrador" }));
        comboCargo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCargoItemStateChanged(evt);
            }
        });
        comboCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCargoActionPerformed(evt);
            }
        });

        lblConvocatoria1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblConvocatoria1.setText("Contraseña:");

        tfContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContrasenaActionPerformed(evt);
            }
        });

        lbArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbArea.setText("Código del área:");

        tfArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAreaActionPerformed(evt);
            }
        });

        lbIdJ.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbIdJ.setText("Identificación del Jefe:");

        tfIdJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdJActionPerformed(evt);
            }
        });

        cbAJ.setText("¿Asignar Jefe?");
        cbAJ.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAJItemStateChanged(evt);
            }
        });
        cbAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAJActionPerformed(evt);
            }
        });

        comboAnos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "67", "68", "69", "70" }));

        lbAnos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbAnos.setText("Años experiencia:");

        tfNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNLActionPerformed(evt);
            }
        });

        lbNL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNL.setText("Numero Licencia:");

        tfEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEspecialidadActionPerformed(evt);
            }
        });

        lbEspecialidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbEspecialidad.setText("Especialidad:");

        tfUniversidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUniversidadActionPerformed(evt);
            }
        });

        lbUniversidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbUniversidad.setText("Universidad:");

        lbHabs1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbHabs1.setText("Habilidades:");

        lbHabs2.setFont(new java.awt.Font("Ubuntu", 2, 12)); // NOI18N
        lbHabs2.setText("<html>Por cada salto de línea se cuenta una habilidad distinta.</html>");

        taHabs.setColumns(20);
        taHabs.setRows(5);
        taHabs.setBorder(null);
        jScrollPane1.setViewportView(taHabs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTelefono)
                            .addComponent(lbNombres)
                            .addComponent(lblNomUsuario)
                            .addComponent(lbCargo))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(tfSalario)
                            .addComponent(tfTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)))
                    .addComponent(cbAJ)
                    .addComponent(lbNL)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbArea)
                            .addComponent(lbEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNL)
                            .addComponent(tfArea)
                            .addComponent(comboEstado, 0, 210, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHabs1)
                            .addComponent(lbHabs2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblConvocatoria1)
                                .addComponent(lbEmail)
                                .addComponent(lbDireccion)
                                .addComponent(lbApellidos))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfContrasena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbIdJ)
                                .addComponent(lbAnos)
                                .addComponent(lbUniversidad))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboAnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfIdJ, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfEspecialidad))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(btCancelar)))
                    .addComponent(lbEspecialidad))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(149, 149, 149)
                                    .addComponent(lbBuscar))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(lbTitulo))
                                .addComponent(lbInfo))
                            .addGap(239, 239, 239))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tfBuscarId, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(175, 175, 175)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNombres)
                            .addComponent(tfNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbApellidos)
                            .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDireccion)
                            .addComponent(lbTelefono)
                            .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEmail)
                            .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomUsuario)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCargo)
                            .addComponent(comboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblConvocatoria1)
                            .addComponent(tfContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfIdJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbIdJ)
                            .addComponent(cbAJ))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbArea)
                            .addComponent(lbAnos)
                            .addComponent(comboAnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEstado)
                            .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEspecialidad)
                            .addComponent(tfEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNL)
                            .addComponent(tfNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbUniversidad)
                            .addComponent(tfUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbHabs1)
                                .addGap(18, 18, 18)
                                .addComponent(lbHabs2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 578, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbTitulo)
                    .addGap(18, 18, 18)
                    .addComponent(lbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lbBuscar)
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(529, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed

        Empleado em;
        em = ce.readEmpleado(tfBuscarId.getText(), 2, 0);
        if (em == null) {
            JOptionPane.showMessageDialog(this, "No se encuentra el usuario en la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            tfNombres.setText(em.getNombres());
            tfApellidos.setText(em.getApellidos());
            tfTelefono.setText(em.getTelefono());
            tfDireccion.setText(em.getDireccion());
            tfSalario.setText(em.getSalario() + "");
            tfEmail.setText(em.getEmail());
            comboCargo.setSelectedItem(em.getCargo());
            tfContrasena.setText(em.getContrasena());
            if (em.getJefe().equals("-1")) {
                cbAJ.setSelected(false);
            } else {
                cbAJ.setSelected(true);
                tfIdJ.setText(em.getJefe());
            }

            if (em.getArea() != null) {
                tfArea.setText(em.getArea().getCodigoArea() + "");
            }

            boolean estado = em.getEstado();
            if (!estado) {
                comboEstado.setSelectedIndex(1);
            } else {
                comboEstado.setSelectedIndex(0);
            }
            System.out.println("cargo " + em.getCargo());
            switch (em.getCargo()) {
                case "Medico":
                    System.out.println("Medico");
                    Medico me = cm.readMedico(em);
                    tfNL.setText(me.getNumeroLicencia() + "");
                    tfEspecialidad.setText(me.getEspecialidad());
                    tfUniversidad.setText(me.getUniversidad());
                    break;
                case "Enfermera":
                    Enfermera enf = cEnf.readEnfermera(em);
                    comboAnos.setSelectedIndex(enf.getAnosExp());
                    String impHabs = "";
                    for (int i = 0; i < enf.getMisHabilidades().length; i++) {
                        impHabs += enf.getMisHabilidades()[i] + "\n";
                    }
                    taHabs.setText(impHabs);
                    break;
            }
        }

    }//GEN-LAST:event_btBuscarActionPerformed

    private void tfBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarIdActionPerformed
        tfBuscarId.setText("");
    }//GEN-LAST:event_tfBuscarIdActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        int result;
        String menj;
        String nombres = tfNombres.getText();
        String identificacion = tfBuscarId.getText();        
        if (tipo == 2) {
            menj = "desactivado";
            int opc = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el usuario " + nombres + "?.\n Favor verificar los datos.");
            if (opc == 0) {
                result = ce.deleteEmpleado(identificacion);

                //Cerramos la ventana
                this.dispose();

                if (result == -1 || result == -2) {
                    JOptionPane.showMessageDialog(this, "Posiblemente estás actualizando a un correo electrónico que ya existe. \n Intente digitando otro correo electrónico. \nSi el problema persiste ha ocurrido un error en la base de datos,consulta al personal encargado", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (result == -3) {//para campos vacíos de enfermera o médico
                        JOptionPane.showMessageDialog(null, "Debe llenar todos los campos para crear el usuario.", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        //Se imprime el mensaje para informar el exito de la operacion
                        JOptionPane.showMessageDialog(this, "El usuario " + nombres + " ha sido " + menj + " con éxito", "Mensaje de éxito", JOptionPane.INFORMATION_MESSAGE);
                        //Cerramos la ventana
                        this.dispose();
                    }
                }
            }

        } else {
            menj = "editado";
            String apellidos = tfApellidos.getText();
            String telefono = tfTelefono.getText();
            String direccion = tfDireccion.getText();
            String salario = tfSalario.getText();
            String email = tfEmail.getText();
            String contrasena = tfContrasena.getText();
            String codigoArea = tfArea.getText();
            String jefe;
            if (cbAJ.isSelected()) {
                jefe = tfIdJ.getText();
            } else {
                jefe = "-1";
            }
            String numLic = "";
            String especialidad = "";
            String universidad = "";
            int anosExperiencia = 0;
            String habs[] = null;
            int cCargo = comboCargo.getSelectedIndex();
            switch (cCargo) {
                case 1://Medico
                    numLic = tfNL.getText();
                    especialidad = tfEspecialidad.getText();
                    universidad = tfUniversidad.getText();
                    break;
                case 2: //Enfermera
                    anosExperiencia = comboAnos.getSelectedIndex();
                    habs = taHabs.getText().split("\n");
                    break;
            }
            String cargo = comboCargo.getSelectedItem().toString();
            System.out.println("cargo" + cargo);
            boolean estado;
            if (comboEstado.getSelectedIndex() == 0) {
                estado = true;
            } else {
                estado = false;
            }

            boolean empty = validateInformation(identificacion, nombres, apellidos, telefono, direccion, salario, email, contrasena, jefe);

            if (empty) {
                JOptionPane.showMessageDialog(null, "Debe llenar todos los campos para crear el usuario.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Area ar;
                try {
                    if (cCargo != 5) {
                        ar = ca.readArea(Integer.parseInt(codigoArea));
                    } else {
                        ar = null;
                    }

                    if (cCargo != 5 && (ar == null || !ar.getEstado())) {
                        JOptionPane.showMessageDialog(this, "Posiblemente estas ingresando un código de un área que no existe o fue desactivada.", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {

                        //Se instancia la clase controlador para hacer uso de ella
                        switch (cCargo) {
                            case 1: //Medico
                                if (especialidad.trim().length() != 0 || universidad.trim().length() != 0) {
                                    result = cm.updateMedico(identificacion, nombres, apellidos, telefono, direccion, Integer.parseInt(salario), email, cargo, contrasena, jefe, ar, estado, Integer.parseInt(numLic), especialidad, universidad);
                                    System.out.println("result: " + result);
                                    if (result == 0) {//si el resultado es 0 es porque el médico no existe, entonces toca crearlo
                                        cm.createMedico(identificacion, nombres, apellidos, telefono, direccion, Integer.parseInt(salario), email, cargo, contrasena, jefe, ar, estado, Integer.parseInt(numLic), especialidad, universidad, 1);
                                        result = ce.updateEmpleado(identificacion, nombres, apellidos, telefono, direccion, Integer.parseInt(salario), email, cargo, contrasena, jefe, ar, estado);
                                    }
                                } else {
                                    result = -3;
                                }
                                break;
                            case 2: //Enfermera
                                if (habs.length != 0) {
                                    result = cEnf.updateEnfermera(identificacion, nombres, apellidos, telefono, direccion, Integer.parseInt(salario), email, cargo, contrasena, jefe, ar, true, anosExperiencia, habs);
                                    System.out.println("result: " + result);
                                    if (result == 0) {//si el resultado es 0 es porque el médico no existe, entonces toca crearlo
                                        cEnf.createEnfermera(identificacion, nombres, apellidos, telefono, direccion, Integer.parseInt(salario), email, cargo, contrasena, jefe, ar, true, anosExperiencia, habs, 1);
                                        result = ce.updateEmpleado(identificacion, nombres, apellidos, telefono, direccion, Integer.parseInt(salario), email, cargo, contrasena, jefe, ar, estado);
                                    }
                                } else {
                                    result = -3;
                                }
                                break;
                            default:
                                result = ce.updateEmpleado(identificacion, nombres, apellidos, telefono, direccion, Integer.parseInt(salario), email, cargo, contrasena, jefe, ar, estado);
                        }
                        if (result == -1 || result == -2) {
                            JOptionPane.showMessageDialog(this, "Posiblemente estás actualizando a un correo electrónico que ya existe. \n Intente digitando otro correo electrónico. \nSi el problema persiste ha ocurrido un error en la base de datos,consulta al personal encargado", "Error", JOptionPane.ERROR_MESSAGE);
                        } else {
                            if (result == -3) {//para campos vacíos de enfermera o médico
                                JOptionPane.showMessageDialog(null, "Debe llenar todos los campos para crear el usuario.", "Error", JOptionPane.ERROR_MESSAGE);
                            } else {
                                //Se imprime el mensaje para informar el exito de la operacion
                                JOptionPane.showMessageDialog(this, "El usuario " + nombres + " ha sido " + menj + " con éxito", "Mensaje de éxito", JOptionPane.INFORMATION_MESSAGE);
                                //Cerramos la ventana
                                this.dispose();
                            }
                        }

                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "El código del área, el salario y número de licencia, en caso del médico, deben ser números enteros.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }


    }//GEN-LAST:event_bModificarActionPerformed
    public boolean validateInformation(String d1, String d2, String d3, String d4, String d5, String d6, String d7, String d8, String d9) {
        return (d1.trim().length() == 0 || d2.trim().length() == 0 || d3.trim().length() == 0 || d4.trim().length() == 0 || d5.trim().length() == 0 || d6.trim().length() == 0 || d7.trim().length() == 0 || d8.trim().length() == 0 || d9.trim().length() == 0);
    }
    private void tfDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDireccionActionPerformed

    private void tfNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombresActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void tfTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefonoActionPerformed

    private void comboCargoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCargoItemStateChanged
        switch (comboCargo.getSelectedIndex()) {
            case 1:
                tfArea.setEditable(true);
                lbAnos.setVisible(false);
                comboAnos.setVisible(false);
                lbNL.setVisible(true);
                tfNL.setVisible(true);
                lbEspecialidad.setVisible(true);
                tfEspecialidad.setVisible(true);
                lbUniversidad.setVisible(true);
                tfUniversidad.setVisible(true);
                lbHabs1.setVisible(false);
                lbHabs2.setVisible(false);
                jScrollPane1.setVisible(false);
                break;
            case 2:
                tfArea.setEditable(true);
                lbAnos.setVisible(true);
                comboAnos.setVisible(true);
                lbNL.setVisible(false);
                tfNL.setVisible(false);
                lbEspecialidad.setVisible(false);
                tfEspecialidad.setVisible(false);
                lbUniversidad.setVisible(false);
                tfUniversidad.setVisible(false);
                lbHabs1.setVisible(true);
                lbHabs2.setVisible(true);
                jScrollPane1.setVisible(true);
                break;
            case 5:
                tfArea.setText("");
                tfArea.setEditable(false);
                lbAnos.setVisible(false);
                comboAnos.setVisible(false);
                lbNL.setVisible(false);
                tfNL.setVisible(false);
                lbEspecialidad.setVisible(false);
                tfEspecialidad.setVisible(false);
                lbUniversidad.setVisible(false);
                tfUniversidad.setVisible(false);
                lbHabs1.setVisible(false);
                lbHabs2.setVisible(false);
                jScrollPane1.setVisible(false);
            default:
                tfArea.setEditable(true);
                lbAnos.setVisible(false);
                comboAnos.setVisible(false);
                lbNL.setVisible(false);
                tfNL.setVisible(false);
                lbEspecialidad.setVisible(false);
                tfEspecialidad.setVisible(false);
                lbUniversidad.setVisible(false);
                tfUniversidad.setVisible(false);
                lbHabs1.setVisible(false);
                lbHabs2.setVisible(false);
                jScrollPane1.setVisible(false);
        }
    }//GEN-LAST:event_comboCargoItemStateChanged

    private void comboCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCargoActionPerformed

    private void tfContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContrasenaActionPerformed

    private void tfAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAreaActionPerformed

    private void tfIdJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdJActionPerformed

    private void cbAJItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAJItemStateChanged
        if (cbAJ.isSelected()) {
            lbIdJ.setVisible(true);
            tfIdJ.setVisible(true);
        } else {
            lbIdJ.setVisible(false);
            tfIdJ.setVisible(false);
        }
    }//GEN-LAST:event_cbAJItemStateChanged

    private void cbAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAJActionPerformed

    private void tfNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNLActionPerformed

    private void tfEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEspecialidadActionPerformed

    private void tfUniversidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUniversidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUniversidadActionPerformed

    private void tfBuscarIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBuscarIdMouseClicked
        tfBuscarId.setSelectionStart(0);
        tfBuscarId.setSelectionEnd(tfBuscarId.getText().length());
    }//GEN-LAST:event_tfBuscarIdMouseClicked

    /**
     * @param args the command line arguments
     */
    /*    public static void main(String args[]) {
     /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    /*    try {
     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
     if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
     }
     }
     } catch (ClassNotFoundException ex) {
     java.util.logging.Logger.getLogger(VistaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (InstantiationException ex) {
     java.util.logging.Logger.getLogger(VistaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (IllegalAccessException ex) {
     java.util.logging.Logger.getLogger(VistaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
     java.util.logging.Logger.getLogger(VistaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     }
     //</editor-fold>

     /* Create and display the form */
    /*     java.awt.EventQueue.invokeLater(new Runnable() {
     public void run() {
     new VistaEditarUsuario(conn).setVisible(true);
     }
     });
     }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bModificar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JCheckBox cbAJ;
    private javax.swing.JComboBox comboAnos;
    private javax.swing.JComboBox comboCargo;
    private javax.swing.JComboBox comboEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAnos;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbArea;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbCargo;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEspecialidad;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbHabs1;
    private javax.swing.JLabel lbHabs2;
    private javax.swing.JLabel lbIdJ;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbNL;
    private javax.swing.JLabel lbNombres;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbUniversidad;
    private javax.swing.JLabel lblConvocatoria1;
    private javax.swing.JLabel lblNomUsuario;
    private javax.swing.JTextArea taHabs;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfArea;
    private javax.swing.JTextField tfBuscarId;
    private javax.swing.JTextField tfContrasena;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEspecialidad;
    private javax.swing.JTextField tfIdJ;
    private javax.swing.JTextField tfNL;
    private javax.swing.JTextField tfNombres;
    private javax.swing.JTextField tfSalario;
    private javax.swing.JTextField tfTelefono;
    private javax.swing.JTextField tfUniversidad;
    // End of variables declaration//GEN-END:variables
}
